if(UNIX)
    set(CPACK_GENERATOR "DEB")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Joel Winarske")
endif()

set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VENDOR "Toyota Connected North America")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "IVI Homescreen - ${CMAKE_BUILD_TYPE}")
set(CPACK_PACKAGE_FILE_NAME ${PROJECT_NAME}-${PROJECT_VERSION}-${CMAKE_BUILD_TYPE}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR})

if(${CMAKE_BUILD_TYPE} STREQUAL "Release")
  set(CPACK_STRIP_FILES lib${PROJECT_NAME}.so)
endif()

set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})

include(CPack)
